(ns com.ozimos.workforce.user-rama.interface
  (:require
   [com.ozimos.workforce.user.interface :as user]))

(def register! user/register!)
(def find-by-id user/find-by-id)
(def find-by-username user/find-by-username)
(def find-by-email user/find-by-email)
(def find-by-identifier user/find-by-identifier)
(def update-username! user/update-username!)
(def verify! user/verify!)
(def change-password! user/change-password!)
(def encode-password user/encode-password)
(def matches-password? user/matches-password?)
(def create-org! user/create-org!)
(def find-org-by-id user/find-org-by-id)
(def find-orgs-for-user user/find-orgs-for-user)
(def get-membership user/get-membership)
(def list-members user/list-members)
(def invite-to-org! user/invite-to-org!)
(def list-invitations-for-user user/list-invitations-for-user)
(def join-org! user/join-org!)
(def switch-org! user/switch-org!)
(def get-active-org user/get-active-org)
(def update-member-role! user/update-member-role!)
(def remove-member! user/remove-member!)
(def create-reset-token! user/create-reset-token!)
(def validate-reset-token user/validate-reset-token)
(def clear-reset-token! user/clear-reset-token!)
